variables:
  # Get Ansible-Autmation secret
  - group: azure_automation

stages:
  - stage: localdev
    displayName: Build Local container
    jobs:

      - job: DockerBuild
        displayName: Build and publish docker images
        variables:
          tag: dev
        steps:

          - task: Docker@2
            displayName: Build Ansible container
            inputs:
              containerRegistry: 'aksbootstrap'
              repository: 'ansible_local'
              command: 'build'
              Dockerfile: 'ansible/DockerFile'
              buildContext: '.'
              tags: |
                $(tag)

          - task: Docker@2
            displayName: Deploy image to aksbootstrap
            inputs:
              containerRegistry: 'aksbootstrap'
              repository: 'ansible_local'
              command: 'push'
              tags: '$(tag)'

  - stage: azdevops
    displayName: Build azure devops containers
    jobs:

      - job: DockerBuild
        displayName: Build and publish docker images
        variables:
          tag: dev
        steps:

          - task: Docker@2
            displayName: Build Ansible container
            inputs:
              containerRegistry: 'aksbootstrap'
              repository: 'ansible_azure'
              command: 'build'
              Dockerfile: 'azure-devops/ansible/DockerFile'
              buildContext: '.'
              tags: |
                $(tag)

          - task: Docker@2
            displayName: Deploy image to aksbootstrap
            inputs:
              containerRegistry: 'aksbootstrap'
              repository: 'ansible_azure'
              command: 'push'
              tags: '$(tag)'



